spring:
  application:
    name: ai-study-mate
  profiles:
    active: dev

# 공통 설정
jwt:
  secret: ${JWT_SECRET}
  access-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}
# OAuth2, cookie 설정은 프로파일별 파일에서 관리

sns:
  appKey: ${KAKAO_CLIENT_ID}
  clientSecret: ${KAKAO_CLIENT_SECRET}
  redirect: http://localhost:9005/login/oauth2/code/kakao
