spring:
  application:
    name: ai-study-mate
  profiles:
    active: dev

  ai:
    openai:
      base-url: https://generativelanguage.googleapis.com/v1beta/openai/
      api-key: ${GEMINI_API_KEY}
      chat:
        completions-path: /chat/completions
        options:
          model: ${GEMINI_MODEL}
          temperature: 0.2
          max-tokens: 2048
    retry:
      on-client-errors: true
      on-http-codes: 429,503
      initial-interval: 500ms
      max-attempts: 3

# 공통 설정
jwt:
  secret: ${JWT_SECRET}
  access-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}
# OAuth2, cookie 설정은 프로파일별 파일에서 관리
